#!/bin/bash
#
#SBATCH --account=132768133143
#SBATCH --job-name=clustFBA-MODEL-N_TS-N_PTS
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=10G
#SBATCH --output=/scratch/user/brubaker/clustFBA/simlogs/clustFBA-MODEL-N_TS-N_PTS.log

## load required modules
module load GCC/12.2.0
module load OpenMPI/4.1.4
module load R_tamu/4.3.1

## enter the simulation directory and execute Rscript
cd /scratch/user/brubaker/clustering-fba/clustFBA-simulations/
echo "STARTING AT `date`"
Rscript clustFBA-simulation.R MODEL N_TS N_PTS N_REP
echo "ENDING AT `date`"
